### ISSUE TITLE
Cant connect - Connection refused by grid

### ISSUE THREAD

**Issue by jesperdc** [soundvibe/ha-danfoss#7]
Hi there, really nice that you made this - iam struggling with the connection to the controller, straight after i push start at the web page it errors out in the app with a error message :-)

And in the browser i see "House was not discovered because of an error: Failed to connect to the sender:"

Any ideas ?! :D 

The logs says::

```
19:33:26.856 [JettyServerThreadPool-Virtual-65] INFO  n.s.h.d.protocol.DanfossDiscovery - Successfully connected to Danfoss grid
19:33:56.864 [JettyServerThreadPool-Virtual-65] ERROR net.soundvibe.hasio.Application - failed to discover a new house
java.lang.RuntimeException: Failed to connect to the sender: 
	at net.soundvibe.hasio.danfoss.protocol.DanfossDiscovery.discover(DanfossDiscovery.java:65)
	at net.soundvibe.hasio.Application.lambda$main$2(Application.java:58)
	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19)
	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:39)
	at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88)
	at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53)
	at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:61)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
Caused by: java.rmi.RemoteException: Connection refused by grid: 1
	at io.github.sonic_amiga.opensdg.java.PeerConnection.startForwarding(PeerConnection.java:92)
	at io.github.sonic_amiga.opensdg.java.PeerConnection.connectToRemote(PeerConnection.java:72)
	at net.soundvibe.hasio.danfoss.protocol.DanfossDiscovery.discover(DanfossDiscovery.java:63)
	... 35 common frames omitted
```

**Comment by soundvibe** [comment]
It looks like Danfoss grid wants you to use different protocol. Not sure how much I could help you with this.
What Danfoss Icon system are you using?

**Comment by jesperdc** [comment]
Hi awesome that you reply - iam using the Danfoss Icon v1 with the app module installed…

![IMG_7534](https://github.com/soundvibe/ha-danfoss/assets/95342820/9c090e7b-69fd-4dae-a8b4-cd1669c7997c)

**Comment by soundvibe** [comment]
Also, what mobile phone are you using for Danfoss app, android or iphone? I've read somewhere that they might work differently and generate different codes. This addon was only tested with android app.

**Comment by jesperdc** [comment]
[log.txt](https://github.com/soundvibe/ha-danfoss/files/14214614/log.txt)
Perfect just updated and change to trace, attached the log here since its pretty long :)

Iam using an iPhone 15 with the latest ios version, think i can grab an Android tomorrow at work and test further if this error message dosent give you something :)

Cool man!

**Comment by soundvibe** [comment]
It doesn't look like full logs. Could you go to HA Settings -> System -> Logs -> Danfoss Icon -> Downlaod full log?

Also, from your system information, the only difference is that my master controller software version is newer (1.9.0).

Would be funny if android app works :D

**Comment by jesperdc** [comment]
Hehe, it works perfect on Android.... :) the only difference i en UI is that the onetimekey is without - in the ios app and in android it shows 2 "-"... but hey it works to go with android :-)

**Comment by soundvibe** [comment]
> Hehe, it works perfect on Android.... :) the only difference i en UI is that the onetimekey is without - in the ios app and in android it shows 2 "-"... but hey it works to go with android :-)

Nice to hear that! I will update the docs to indicate that only Danfoss android app is supported :) 
I think that even the one time code looks similar, it might be that iphone code is "bound" to different protocol  and that's why it fails.

**Comment by soundvibe** [comment]
@jesperdc 

Also, you can revert addon's log level to info now, otherwise it will spam you with unnecessary logs.

**Comment by jesperdc** [comment]
Heh yep done that, and added the Mqtt aswell - awesome work you have done here, that saved me for changing to the zigbee model 😜👌🏻

**Comment by jesperdc** [comment]
Hmm just a Quick question - the battery level is not presented in the entity sensor.danfoss_xx_battery_level :-) ?

**Comment by soundvibe** [comment]
> Hmm just a Quick question - the battery level is not presented in the entity sensor.danfoss_xx_battery_level :-) ?

Currently, it's presented as sensor.danfoss.xx.temperature as `battery_level` attribute, e.g.:
```yaml
{{ state_attr("sensor.danfoss_15_temperature", "battery_level") }}
```

**Comment by topt** [comment]
that's great news - indeed... I only tried with a bunch of different iPhones. I now used an Android Emulator (genymotion.com) and was able to share the house to this emu first, and from there to this plugin, which worked! Thanks to all!
